version: '3.0'

services:
  db:
    image: postgres:14.2
    environment:
      - POSTGRES_PASSWORD=root
      - PGDATA=/var/lib/postgresql/data/pgdata 
    volumes:
      - ./.dbdata:/var/lib/postgresql/data 